export const WORKS = [
    { id: 1, title: "등대", category: "금속", imageSrc: "/METAL/6.jpg" },
    { id: 2, title: "키티", category: "FRP", imageSrc: "/FRP/4.jpg" },
    { id: 3, title: "과일나무", category: "스티로폼", imageSrc: "/STYROFOAM/4.jpg" },
    { id: 4, title: "조형물", category: "금속", imageSrc: "/METAL/12.jpg" },
    { id: 5, title: "토끼", category: "FRP", imageSrc: "/FRP/6.jpg" },
    { id: 6, title: "왕", category: "FRP", imageSrc: "/FRP/8.jpg" },
    { id: 7, title: "FRP 작품 7", category: "FRP", imageSrc: "/FRP/7.jpg" },
    { id: 8, title: "FRP 작품 8", category: "FRP", imageSrc: "/FRP/12.jpg" },
    { id: 9, title: "FRP 작품 9", category: "FRP", imageSrc: "/FRP/11.jpg" },
    { id: 10, title: "FRP 작품 10", category: "FRP", imageSrc: "/FRP/1.jpg" },
    { id: 11, title: "FRP 작품 11", category: "FRP", imageSrc: "/FRP/5.jpg" },
    { id: 12, title: "FRP 작품 12", category: "FRP", imageSrc: "/FRP/14.jpg" },
    { id: 13, title: "FRP 작품 13", category: "FRP", imageSrc: "/FRP/13.jpg" },
    { id: 14, title: "FRP 작품 14", category: "FRP", imageSrc: "/FRP/10.jpg" },
    { id: 15, title: "FRP 작품 15", category: "FRP", imageSrc: "/FRP/3.jpg" },
    { id: 16, title: "FRP 작품 16", category: "FRP", imageSrc: "/FRP/2.jpg" },
    { id: 17, title: "FRP 작품 17", category: "FRP", imageSrc: "/FRP/9.jpg" },
    { id: 18, title: "스티로폼 작품 18", category: "스티로폼", imageSrc: "/STYROFOAM/7.jpg" },
    { id: 19, title: "스티로폼 작품 19", category: "스티로폼", imageSrc: "/STYROFOAM/11.jpg" },
    { id: 20, title: "스티로폼 작품 20", category: "스티로폼", imageSrc: "/STYROFOAM/6.jpg" },
    { id: 21, title: "스티로폼 작품 21", category: "스티로폼", imageSrc: "/STYROFOAM/1.jpg" },
    { id: 22, title: "스티로폼 작품 22", category: "스티로폼", imageSrc: "/STYROFOAM/5.jpg" },
    { id: 23, title: "스티로폼 작품 23", category: "스티로폼", imageSrc: "/STYROFOAM/10.jpg" },
    { id: 24, title: "스티로폼 작품 24", category: "스티로폼", imageSrc: "/STYROFOAM/3.jpg" },
    { id: 25, title: "스티로폼 작품 25", category: "스티로폼", imageSrc: "/STYROFOAM/2.jpg" },
    { id: 26, title: "스티로폼 작품 26", category: "스티로폼", imageSrc: "/STYROFOAM/8.jpg" },
    { id: 27, title: "스티로폼 작품 27", category: "스티로폼", imageSrc: "/STYROFOAM/9.jpg" },
    { id: 28, title: "금속 작품 28", category: "금속", imageSrc: "/METAL/7.jpg" },
    { id: 29, title: "금속 작품 29", category: "금속", imageSrc: "/METAL/4.jpg" },
    { id: 30, title: "금속 작품 30", category: "금속", imageSrc: "/METAL/11.jpg" },
    { id: 31, title: "금속 작품 31", category: "금속", imageSrc: "/METAL/5.jpg" },
    { id: 32, title: "금속 작품 32", category: "금속", imageSrc: "/METAL/14.jpg" },
    { id: 33, title: "금속 작품 33", category: "금속", imageSrc: "/METAL/13.jpg" },
    { id: 34, title: "금속 작품 34", category: "금속", imageSrc: "/METAL/10.jpg" },
    { id: 35, title: "금속 작품 35", category: "금속", imageSrc: "/METAL/1.png" },
    { id: 36, title: "금속 작품 36", category: "금속", imageSrc: "/METAL/3.jpg" },
    { id: 37, title: "금속 작품 37", category: "금속", imageSrc: "/METAL/2.jpg" },
    { id: 38, title: "금속 작품 38", category: "금속", imageSrc: "/METAL/8.jpg" },
    { id: 39, title: "금속 작품 39", category: "금속", imageSrc: "/METAL/9.jpg" },
    { id: 40, title: "기타 작품 40", category: "기타", imageSrc: "/ETC/7.jpg" },
    { id: 41, title: "기타 작품 41", category: "기타", imageSrc: "/ETC/4.jpg" },
    { id: 42, title: "기타 작품 42", category: "기타", imageSrc: "/ETC/6.jpg" },
    { id: 43, title: "기타 작품 43", category: "기타", imageSrc: "/ETC/1.jpg" },
    { id: 44, title: "기타 작품 44", category: "기타", imageSrc: "/ETC/5.jpg" },
    { id: 45, title: "기타 작품 45", category: "기타", imageSrc: "/ETC/10.jpg" },
    { id: 46, title: "기타 작품 46", category: "기타", imageSrc: "/ETC/3.jpg" },
    { id: 47, title: "기타 작품 47", category: "기타", imageSrc: "/ETC/2.jpg" },
    { id: 48, title: "기타 작품 48", category: "기타", imageSrc: "/ETC/8.JPG" },
    { id: 49, title: "기타 작품 49", category: "기타", imageSrc: "/ETC/9.jpg" },
];
